message: 
  updated->fromDevVitalSignyml
spring:
  data:
     mongodb:
        auto-index-creation: true
        database: VitalSign
        host: localhost
        port: 27017
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 600000
  redis:
    host: localhost
    port: 6379
    
healthcare:
  management: 
   user:
     uri: http://localhost:8080/users
     name: Healthcare-Management-User-API 
   patient:
    uri: http://localhost:8089/patient
    name: Healthcare-Management-Patient-API
   queue: vitalSign_queue
   exchange: vitalSign_exchange
   routingqueue: vitalSign_routingqueue
